### PR TITLE
patch: fine tune sendgrid sdk rule

### PR DESCRIPTION
**Pull request by abhstabs**

### CODE REVIEW

**Review by khemrajrathore — COMMENTED** [review]
@pandurangpatil Add your comments for this PR

**Review by HiteshMah-Jan — COMMENTED** [review]
Can we add some more method names which share data, else we'll lose coverage.

**Review by HiteshMah-Jan — APPROVED** [review]

**Comment by khemrajrathore** [comment]
I guess we can close this PR, @abhstabs ?

**Comment by abhstabs** [comment]
It is decided to not tune the rules so that we can have sufficient coverage of codebase. Closing the PR.

**Pull request closed without merging**
