### PR TITLE
Javascript storage

### PR DESCRIPTION
**Pull request by khemrajrathore**
Rule for Express Collection Point detection

### CODE REVIEW

**Comment by ojaswa1942** [comment]
What does the `express` in pattern signifies? Will the work only when the variable name is `express`?

**Comment by khemrajrathore** [comment]
@ojaswa1942 `express` significy the third party `express`

**Review by ojaswa1942 — CHANGES_REQUESTED** [review]
Okay, will `methodFullName` not have multiple things in between?
Example: 

```
const express = require('express');
const { withAuth } = require('../utils/middlewares');

const router = express.Router();
router.use(withAuth);
router.get('/:id', getProduct);
```

1. Here: `get` should be `pkg.express.Router.get`, and `express.get` will not match.
2. Let's also include more [routing methods](https://expressjs.com/en/4x/api.html#routing-methods) supported by express, especially the common ones, including: `delete`, `put`, `patch`, `head`, `subscribe`, `unsubscribe`.

**Review by ojaswa1942 — APPROVED** [review]
:shipit:

**Pull request merged**
